# Generated by Django 4.2.1 on 2024-08-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='received_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
