# Generated by Django 4.2.1 on 2024-08-03 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_payment_received_amount_payment_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='total_amount',
            new_name='sum_amount',
        ),
    ]
